version: '3'
services:
  novel-api:
    #image: 4maxcheck/novel-api-arm:latest
    image: 4maxcheck/novel-api-x86:latest
    volumes:
      - './keys/tokens:/root/keys/tokens'
      - './keys/tokens_err:/root/keys/tokens_err'
      - './config.yml:/root/config.yml'
    container_name: novel-api
    ports:
      - '3388:3388'
    tty: true
    stdin_open: true
